### ISSUE TITLE
Linux version crashes when I want open file by menu File->Open...

### ISSUE THREAD

**Issue by sdorof1** [icons8/lunacy-docs#74]
Lunacy version 8.7.2
OS: Ubuntu 22.04

Exception:

```
Unhandled exception. System.Exception: Unable to initialize GTK on separate thread
   at Avalonia.X11.NativeDialogs.GtkSystemDialog.EnsureInitialized()
   at Avalonia.X11.NativeDialogs.GtkSystemDialog.ShowFileDialogAsync(FileDialog dialog, Window parent)
   at Lunacy.Services.DialogService.<>c__DisplayClass7_0.<<OpenFileDialogAsync>b__0>d.MoveNext() in /root/parts/lunacy/build/Lunacy/Lunacy.UI/Services/DialogService.cs:line 193
--- End of stack trace from previous location ---
   at Lunacy.Services.DialogService.OpenFileDialogAsync(String[] fileTypeFilter, String fileName, String initialDirectory, Boolean multiSelect) in /root/parts/lunacy/build/Lunacy/Lunacy.UI/Services/DialogService.cs:line 191
   at Lunacy.Services.DialogService.OpenFileAsync(String fileName, String initialDirectory, String[] fileTypeFilter) in /root/parts/lunacy/build/Lunacy/Lunacy.UI/Services/DialogService.cs:line 123
   at Lunacy.ViewModels.TabsViewModel.OpenFileAsync(IFileContentSource fileSource, Boolean addToMRU, Boolean isTemplate) in /root/parts/lunacy/build/Lunacy/Lunacy.Shared/ViewModels/TabsViewModel.cs:line 859
   at Lunacy.Threading.TaskExtensions.DoNotWait(Task task) in /root/parts/lunacy/build/Lunacy/Lunacy.Threading/TaskExtensions.cs:line 10
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.X11.X11PlatformThreading.HandleX11(CancellationToken cancellationToken)
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at Lunacy.Program.Main(String[] args) in /root/parts/lunacy/build/Lunacy/Lunacy/Program.cs:line 16
```

**Comment by Mikolaytis** [comment]
This is not our bug tracker. Here we accept only documentation-related issues.
Please, report new bugs here: https://community.icons8.com/c/lunacy/7

About issue - I hope it fixed in the recent updates. If not - contact as via community forum. Thanks!
